import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import CategoryDropdown from "../components/CategoryDropdown";
import FloatingActionButton from "../components/FloatingActionButton";
import ProductList from "../components/products/ProductList";
import Searchbar from "../components/Searchbar";
import Category from "../types/Category";
import Product from "../types/Product";

const Home: NextPage = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [shownProductIndexes, setShownProductIndexes] = useState<number[]>([]);
  const [category, setCategory] = useState<Category>({ name: "", id: "" });

  useEffect(() => {
    getProducts();
  }, []);

  const getProducts = async () => {
    const url =
      "https://62286b649fd6174ca82321f1.mockapi.io/case-study/products";
    const response = await fetch(url);
    const data = await response.json();
    setProducts(data);
    setShownProductIndexes(data.map((data, i) => i));
  };

  return (
    <div>
      <Head>
        <title>Welcome to My Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="relative p-10">
          <div className="w-full max-w-screen-xl mx-auto">
            <div className="flex flex-col justify-between md:flex-row ">
              <Searchbar
                products={products}
                setShownProductIndexes={setShownProductIndexes}
              />
              <CategoryDropdown setCategory={setCategory} />
            </div>
            <ProductList
              products={products}
              shownProductIndexes={shownProductIndexes}
              category={category}
            />
          </div>
          <FloatingActionButton />
        </div>
      </main>
    </div>
  );
};

export default Home;
